"use client";
import { useEffect, useState } from "react";

type Q = { id: string; difficulty: string; theme: string; text: string; options: string[]; correct_option: number; verse_reference: string; explanation: string; points: number; is_active: boolean };
type S = Record<string, any>;
export default function TestConnaissanceBibliqueAdminPanel() {
  const [settings, setSettings] = useState<S>({ title: "TEST CONNAISSANCE BIBLIQUE", subtitle: "", is_active: true, easy_seconds: 45, medium_seconds: 90, hard_seconds: 135, expert_seconds: 180, easy_points: 10, medium_points: 15, hard_points: 20, expert_points: 25 });
  const [questions, setQuestions] = useState<Q[]>([]); const [editing, setEditing] = useState<Partial<Q> | null>(null); const [json, setJson] = useState(""); const [message, setMessage] = useState("");
  async function load() { const r = await fetch("/api/quiz/admin"); const j = await r.json(); if (j.settings) setSettings(j.settings); setQuestions(j.questions || []); }
  useEffect(() => { load(); }, []);
  async function saveSettings(e: React.FormEvent) { e.preventDefault(); const publicContent = { hero_support: settings.hero_support, intro_title: settings.intro_title, intro_text: settings.intro_text, challenge_title: settings.challenge_title, challenge_text: settings.challenge_text, signoff: settings.signoff }; const isPublicForm = (e.currentTarget as HTMLFormElement).dataset.kind === "public"; const r = await fetch(isPublicForm ? "/api/site-settings" : "/api/quiz/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(isPublicForm ? publicContent : settings) }); setMessage(r.ok ? "Réglages enregistrés." : ((await r.json().catch(() => ({}))).error || "Erreur d'enregistrement.")); }
  async function importQuestions() { try { const parsed = JSON.parse(json); const r = await fetch("/api/quiz/admin", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(parsed) }); const j = await r.json(); setMessage(r.ok ? `${j.imported} question(s) importée(s).` : j.error); if (r.ok) { setJson(""); load(); } } catch { setMessage("JSON invalide."); } }
  async function saveQuestion() { if (!editing) return; const r = await fetch("/api/quiz/admin", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(editing) }); setMessage(r.ok ? "Question enregistrée." : "Erreur."); if (r.ok) { setEditing(null); load(); } }
  async function remove(id: string) { if (!confirm("Supprimer cette question ?")) return; await fetch(`/api/quiz/admin?id=${id}`, { method: "DELETE" }); load(); }
  return <div>
    <div className="card"><h2>Contenus publics</h2><p className="muted">Modifie les textes visibles sur l’accueil sans toucher au code.</p><form onSubmit={saveSettings} data-kind="public">
      {[['title','Nom du défi'],['subtitle','Sous-titre du défi'],['hero_support','Phrase d’accroche'],['intro_title','Titre de la section découverte'],['intro_text','Texte de la section découverte'],['challenge_title','Titre du défi du moment'],['challenge_text','Texte du défi du moment'],['signoff','Signature de l’accueil']].map(([key,label]) => <div key={key}><label>{label}</label><input value={settings[key] || ''} onChange={e => setSettings({...settings, [key]: e.target.value})} /></div>)}
      <button className="btn">Enregistrer les contenus</button>
    </form></div>
    <div className="card"><h2>Réglages du défi</h2><p className="muted">Gestion réservée au super-admin : réglages et banque de questions.</p><form onSubmit={saveSettings} data-kind="quiz">
      <label>Titre public</label><input value={settings.title || ""} onChange={e => setSettings({...settings, title: e.target.value})} />
      <label>Sous-titre</label><input value={settings.subtitle || ""} onChange={e => setSettings({...settings, subtitle: e.target.value})} />
      <label><input type="checkbox" checked={!!settings.is_active} onChange={e => setSettings({...settings, is_active: e.target.checked})} /> Test actif</label>
      <div className="form-grid">{[["easy_seconds","Facile secondes"],["medium_seconds","Moyen secondes"],["hard_seconds","Difficile secondes"],["expert_seconds","Expert secondes"],["easy_points","Facile points"],["medium_points","Moyen points"],["hard_points","Difficile points"],["expert_points","Expert points"]].map(([key,label]) => <div key={key}><label>{label}</label><input type="number" min="1" value={settings[key]} onChange={e => setSettings({...settings, [key]: Number(e.target.value)})} /></div>)}</div>
      <button className="btn">Enregistrer les réglages</button>
    </form></div>
    <div className="card"><h2>Importer une base JSON</h2><p className="muted">Import direct de questions structurées.</p><textarea rows={7} value={json} onChange={e => setJson(e.target.value)} placeholder='[{"external_id":"q-001","difficulty":"facile","theme":"Genèse","text":"...","options":["...","..."],"correctOption":0,"points":10}]' /><button className="btn" type="button" onClick={importQuestions}>Importer la base JSON</button></div>
    {message && <div className="success-box">{message}</div>}
    <div className="card"><h2>Banque de questions ({questions.length})</h2>{questions.map(q => <div key={q.id} className="question-block"><div className="row-between"><div><strong>{q.text}</strong><div className="muted">{q.difficulty} · {q.theme} · {q.points} points</div></div><div><button className="btn secondary small" onClick={() => setEditing({...q})}>Modifier</button> <button className="btn danger small" onClick={() => remove(q.id)}>Supprimer</button></div></div></div>)}</div>
    {editing && <div className="card"><h2>Modifier la question</h2><label>Question</label><textarea value={editing.text || ""} onChange={e => setEditing({...editing, text: e.target.value})} /><label>Difficulté</label><select value={editing.difficulty} onChange={e => setEditing({...editing, difficulty: e.target.value})}><option>facile</option><option>moyen</option><option>difficile</option><option>expert</option></select><label>Thème</label><input value={editing.theme || ""} onChange={e => setEditing({...editing, theme: e.target.value})} /><label>Points</label><input type="number" value={editing.points || 1} onChange={e => setEditing({...editing, points: Number(e.target.value)})} />{(editing.options || []).map((o,i) => <input key={i} value={o} onChange={e => { const options=[...(editing.options || [])]; options[i]=e.target.value; setEditing({...editing, options}); }} />)}<label>Index de la bonne réponse</label><input type="number" value={editing.correct_option ?? 0} onChange={e => setEditing({...editing, correct_option: Number(e.target.value)})} /><label>Référence biblique</label><input value={editing.verse_reference || ""} onChange={e => setEditing({...editing, verse_reference: e.target.value})} /><label>Explication</label><textarea value={editing.explanation || ""} onChange={e => setEditing({...editing, explanation: e.target.value})} /><button className="btn" onClick={saveQuestion}>Enregistrer</button> <button className="btn secondary" onClick={() => setEditing(null)}>Annuler</button></div>}
  </div>;
}
